require("adib.plugins")
require("adib.after.lualine")
require("adib.after.lsp")
require("adib.after.oil")
require("adib.after.treesitter")
require("adib.after.core")
require("adib.after.telescope")
require("adib.after.icon")
require("adib.after.mapping")
require("adib.after.lint")
require("adib.after.confront")
require("adib.after.snip")

